export { default as MainPage} from "./MainPage"
export { default as Login} from "./Login"
export { default as SignUp} from "./SignUp"
export { default as Profile} from "./Profile"
export { default as Projects} from "./Projects"
export { default as Project} from "./Project"
export { default as Tasks} from "./Tasks"
export { default as Task} from "./Task"
export {default as Dashboard} from "./Dasboard"
